import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh
 */
public class acc_details extends javax.swing.JFrame {

    /**
     * Creates new form acc_details
     */
    public acc_details() {
        initComponents();
    }

     public acc_details(String para){
        initComponents();
        String i=para;
        l3.setText(para);
        
    try{
    
    Class.forName("java.sql.DriverManager");
    com.mysql.jdbc.Connection con=(com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/tour","root","12345");
        Statement stmt=(Statement) con.createStatement();
        String query="SELECT * from signup where username='"+i+"';";
        ResultSet rs= stmt.executeQuery(query);
        while(rs.next()){
            String first_name=rs.getString("first_name");
            String last_name=rs.getString("last_name");
            String phone_no=rs.getString("phone_no");
            String wallet=rs.getString("wallet"); 
            l1.setText(first_name);
            l2.setText(last_name);
            l3.setText(i);
            l4.setText(phone_no);
            l5.setText(wallet);
    } }
    catch(Exception e){
         JOptionPane.showMessageDialog(null,e);}
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset_hint = new javax.swing.JLabel();
        reset_pass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reset_hint.setFont(new java.awt.Font("Amatic", 1, 36)); // NOI18N
        reset_hint.setForeground(new java.awt.Color(255, 255, 255));
        reset_hint.setText("        RESET  HINT");
        reset_hint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        reset_hint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_hint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_hintMouseClicked(evt);
            }
        });
        getContentPane().add(reset_hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 170, 50));

        reset_pass.setFont(new java.awt.Font("Amatic", 1, 36)); // NOI18N
        reset_pass.setForeground(new java.awt.Color(255, 255, 255));
        reset_pass.setText("    RESET  PASSWORD");
        reset_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        reset_pass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_passMouseClicked(evt);
            }
        });
        getContentPane().add(reset_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 170, 50));

        jLabel2.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current  wallet  balance         :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 240, 40));

        l5.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        l5.setForeground(new java.awt.Color(0, 255, 204));
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 230, 40));

        l4.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        l4.setForeground(new java.awt.Color(0, 255, 204));
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 230, 40));

        l3.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        l3.setForeground(new java.awt.Color(0, 255, 204));
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 230, 40));

        l2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 255, 204));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 230, 40));

        l1.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 255, 204));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 230, 40));

        jLabel5.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last  Name                                           :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 240, 40));

        jLabel3.setFont(new java.awt.Font("Amatic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   ACCOUNT  DETAILS");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 180, 60));

        jLabel6.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username                                            :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 270, 40));

        jLabel7.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone  no.                                          :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 260, 40));

        jLabel8.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First  Name                                         :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 40));

        jLabel4.setFont(new java.awt.Font("Amatic", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<-  BACK");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account detalis.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
this.setVisible(false);
new home().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void reset_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_passMouseClicked
String username=l3.getText();
  new reset_password(username).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_reset_passMouseClicked

    private void reset_hintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_hintMouseClicked
String username=l2.getText();
        new reset_hint(username).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_reset_hintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acc_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acc_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acc_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acc_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acc_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel reset_hint;
    private javax.swing.JLabel reset_pass;
    // End of variables declaration//GEN-END:variables
}
