import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh
 */
public class reset_password extends javax.swing.JFrame {

    /**
     * Creates new form reset_password
     */
    public reset_password() {
        initComponents();
    }
reset_password(String username) {
    initComponents();
       String i=username;
       l1.setVisible(false);
       l1.setText(i);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, 60));

        jLabel6.setFont(new java.awt.Font("Amatic", 0, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<- BACK");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 50));

        jLabel2.setFont(new java.awt.Font("Amatic", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  NEW  password        :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 50));

        reset.setFont(new java.awt.Font("Amatic", 0, 30)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText("                RESET  ");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0)));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, 40));

        jLabel4.setFont(new java.awt.Font("Amatic", 0, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  OLD  password         :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 140, 50));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 210, 30));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 210, 30));

        jLabel5.setFont(new java.awt.Font("Amatic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("  RESET  PASSWORD");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 130, 50));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small frames .jpg"))); // NOI18N
        getContentPane().add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
this.setVisible(false);
new acc_details().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
    int j=0; 
        try{
    Class.forName("java.sql.DriverManager");
    com.mysql.jdbc.Connection con=(com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/tour","root","12345");
        Statement stmt=(Statement) con.createStatement();
        String query="Update signup set password='"+t2.getText()+"' where username='"+l1.getText()+"' and password='"+t1.getText()+"';";
        PreparedStatement pst=con.prepareStatement(query);  
        pst.executeUpdate(query);
        String query1="Select * from signup where username='"+l1.getText()+"' and password='"+t2.getText()+"';";
        PreparedStatement pst1=con.prepareStatement(query1);  
        ResultSet rs=pst1.executeQuery(query1);
        if (rs.next())
        {
            JOptionPane.showMessageDialog(null,"Successfully Changed");
            j++;
            this.setVisible(false);
                    }
        if(j==0)
        JOptionPane.showMessageDialog(this,"Please enter correct details");
        
    } 
    catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
}
        
        
    }//GEN-LAST:event_resetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reset_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reset_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel reset;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
