     import java.sql.*;
     import java.awt.*;
     import javax.swing.*;
     import java.awt.event.*;
     import javax.swing.JOptionPane;
     import java.sql.DriverManager;
     import com.mysql.jdbc.Connection;
     import com.mysql.jdbc.Statement;
     /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh
 */
public class sign_in extends javax.swing.JFrame {

    /**
     * Creates new form sign_in
     */
    public sign_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fpass = new javax.swing.JLabel();
        terms = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 210, 260, 30));

        l1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 150, 260, 30));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    LOGIN");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 120, 50));

        fpass.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        fpass.setForeground(new java.awt.Color(204, 204, 255));
        fpass.setText("forget password");
        fpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpassMouseClicked(evt);
            }
        });
        getContentPane().add(fpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 170, 30));
        getContentPane().add(terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("|");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 34, 30));

        account.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        account.setForeground(new java.awt.Color(204, 204, 255));
        account.setText(" create an account");
        account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
        });
        getContentPane().add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, 230, 30));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 260, 30));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 260, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\aryan\\ip project\\final frames\\signIN.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
if(terms.isSelected()==true){
String t1=username.getText();
String t2=password.getText();
int i=0;
int j=0;
{ if (t1.trim().isEmpty()&&t2.trim().isEmpty()){
            i=1;
           JOptionPane.showMessageDialog(this,"Please enter Usename and password");}
else {
        if(t1.trim().isEmpty()){
           i=1;
            l1.setText("Enter Your Username");}
        if(t2.trim().isEmpty()){
            i=1;
            l2.setText("Enter Your Password");
        }       } }
        {
if (i==0){
    try{
    
    Class.forName("java.sql.DriverManager");
        com.mysql.jdbc.Connection con=(com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/tour","root","12345");
        com.mysql.jdbc.Statement stmt=(com.mysql.jdbc.Statement) con.createStatement();
        String query="SELECT * from signup where username=? and password=?;";
        PreparedStatement pst=con.prepareStatement(query);
        pst.setString(1,username.getText());
        pst.setString(2,password.getText());
        ResultSet rs= pst.executeQuery();
        if(rs.next()){
        this.setVisible(false);
        new home(t1).setVisible(true);
        j++;
        } 
    if (j==0)
        JOptionPane.showMessageDialog(this,"Username and Password didn't Match");
    }
    catch(Exception e){
         JOptionPane.showMessageDialog(null,e);}
     }
            }


}
     else {
        JOptionPane.showMessageDialog(this,"Please agree with all the terms & condition");
}

    }//GEN-LAST:event_jLabel2MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void fpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpassMouseClicked
this.setVisible(false);
new forget_pass().setVisible(true);
    }//GEN-LAST:event_fpassMouseClicked

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
      this.setVisible(false);
      new sign_up().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_accountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JLabel fpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton terms;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
