import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mahesh
 */
public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        last_name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        hint = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        phone_no = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        retype = new javax.swing.JTextField();
        enter_lastname = new javax.swing.JLabel();
        enter_username = new javax.swing.JLabel();
        enter_phoneno = new javax.swing.JLabel();
        enter_password = new javax.swing.JLabel();
        enter_retype = new javax.swing.JLabel();
        enter_hint = new javax.swing.JLabel();
        enter_firstname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 280, 30));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 280, 30));
        getContentPane().add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 280, 30));
        getContentPane().add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 280, 30));
        getContentPane().add(phone_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 280, 30));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 280, 30));
        getContentPane().add(retype, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 280, 30));

        enter_lastname.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_lastname.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 30, 30));

        enter_username.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_username.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 30, 30));

        enter_phoneno.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_phoneno.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 30, 30));

        enter_password.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_password.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 30, 30));

        enter_retype.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        enter_retype.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_retype, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 320, 30));

        enter_hint.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_hint.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 40, 30));

        enter_firstname.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        enter_firstname.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(enter_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   SUBMIT");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign_up.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sign_up.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
String t1=first_name.getText();
String t2=last_name.getText();
String t3=username.getText();
String t4=phone_no.getText();
String t5=password.getText();
String t6=retype.getText();
String t7=hint.getText();  
enter_firstname.setText("");
enter_lastname.setText("");
enter_username.setText("");
enter_phoneno.setText("");
enter_password.setText("");
enter_retype.setText("");
enter_hint.setText("");

int i=0;
if(t1.trim().isEmpty()){i=1;
enter_firstname.setText("X");}
if(t2.trim().isEmpty()){i=1;
enter_lastname.setText("X");}
if(t3.trim().isEmpty()){i=1;
enter_username.setText("X");}
if(t4.trim().isEmpty()){i=1;
enter_phoneno.setText("X");}
if(t5.trim().isEmpty()){i=1;
enter_password.setText("X");}
if(t6.trim().isEmpty()){i=1;
enter_retype.setText("X");}
if(t7.trim().isEmpty()){i=1;
enter_hint.setText("X");}

if (i==0){
    if(t5.trim().equals(t6.trim()))
    {try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/tour","root","12345");
        Statement stmt=(Statement) con.createStatement();
        String query="INSERT INTO signup VALUES('"+t1+"','"+t2+"','"+t3+"','"+t4+"','"+t5+"','"+t7+" ','  "+0+ "  ' );";
        stmt.executeUpdate(query);
        new sign_in().setVisible(true);
        this.setVisible(false);
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
    }
        }

else {
            enter_retype.setText("PASSWORD DID NOT MATCH");
            }
}
else JOptionPane.showMessageDialog(this,"All Fields are Compulsory");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enter_firstname;
    private javax.swing.JLabel enter_hint;
    private javax.swing.JLabel enter_lastname;
    private javax.swing.JLabel enter_password;
    private javax.swing.JLabel enter_phoneno;
    private javax.swing.JLabel enter_retype;
    private javax.swing.JLabel enter_username;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField hint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phone_no;
    private javax.swing.JTextField retype;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
