import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mahesh
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
       
    }
   
   
    
    
     public transaction(String para){
    initComponents();
    username.setText(para);
    String i=username.getText();
     name.setVisible(false);
cvv.setVisible(false);
cardno.setVisible(false);
expdate.setVisible(false);  
    try{
    
    Class.forName("java.sql.DriverManager");
    com.mysql.jdbc.Connection con=(com.mysql.jdbc.Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/tour","root","12345");
        Statement stmt=(Statement) con.createStatement();
        String query="SELECT * from signup where username='"+i+"';";
        ResultSet rs= stmt.executeQuery(query);
        while(rs.next()){
            
            
            String wallet=rs.getString("wallet"); 
           
            user.setText("RS."+wallet);
    } }
    catch(Exception e){
         JOptionPane.showMessageDialog(null,e);}  
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bw1 = new javax.swing.JButton();
        bc1 = new javax.swing.JButton();
        cvv = new javax.swing.JTextField();
        cardno = new javax.swing.JTextField();
        expdate = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        user = new javax.swing.JLabel();
        wallet1 = new javax.swing.JRadioButton();
        credit = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        amount1 = new javax.swing.JLabel();
        lable = new javax.swing.JLabel();
        username = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bw1.setBackground(new java.awt.Color(153, 153, 153));
        bw1.setFont(new java.awt.Font("Amatic", 0, 36)); // NOI18N
        bw1.setText("PAYMENT");
        bw1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bw1MouseClicked(evt);
            }
        });
        getContentPane().add(bw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 50));

        bc1.setBackground(new java.awt.Color(153, 153, 153));
        bc1.setFont(new java.awt.Font("Amatic", 0, 36)); // NOI18N
        bc1.setText("PAYMENT");
        bc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bc1MouseClicked(evt);
            }
        });
        getContentPane().add(bc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 170, 50));
        getContentPane().add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 220, 30));
        getContentPane().add(cardno, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 30));
        getContentPane().add(expdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 220, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 220, 30));

        user.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(0, 255, 0));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 180, 40));

        buttonGroup1.add(wallet1);
        wallet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wallet1MouseClicked(evt);
            }
        });
        getContentPane().add(wallet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        buttonGroup1.add(credit);
        credit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditMouseClicked(evt);
            }
        });
        getContentPane().add(credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, 20));

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Card details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 450, 210));
        getContentPane().add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 140, 40));

        lable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaction.jpg"))); // NOI18N
        getContentPane().add(lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        username.setText("jLabel2");
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 180, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditMouseClicked
name.setVisible(true);
cvv.setVisible(true);
cardno.setVisible(true);
expdate.setVisible(true);
bw1.setVisible(false);
bc1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_creditMouseClicked

    private void bc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bc1MouseClicked
  String n1=name.getText();
  String n2=lable.getText();
  JOptionPane.showMessageDialog(this,"Dear, "+n1+"  your payment for the trip has been successfully done!");
       this.setVisible(false);
       new home(n2).setVisible(true);
        
    }//GEN-LAST:event_bc1MouseClicked

    private void bw1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bw1MouseClicked
String n1=name.getText();
  String n2=user.getText();
  
        
// TODO add your handling code here:
    }//GEN-LAST:event_bw1MouseClicked

    private void wallet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wallet1MouseClicked
  name.setVisible(false);
cvv.setVisible(false);
cardno.setVisible(false);
expdate.setVisible(false);
bw1.setVisible(true);
bc1.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_wallet1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel amount1;
    private javax.swing.JButton bc1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton bw1;
    private javax.swing.JTextField cardno;
    private javax.swing.JRadioButton credit;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField expdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lable;
    private javax.swing.JTextField name;
    private javax.swing.JLabel user;
    private javax.swing.JLabel username;
    private javax.swing.JRadioButton wallet1;
    // End of variables declaration//GEN-END:variables
}
